/*
 * MIT License
 *
 * Copyright (c) Copyright (c) 2017-2017, Greatmancode
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package com.greatmancode.legendarybot.commands.affix;

import net.dv8tion.jda.core.EmbedBuilder;
import org.joda.time.DateTime;
import org.joda.time.DateTimeZone;

import java.awt.*;
import java.util.HashMap;
import java.util.Map;

/**
 * Several utils to calculate what affixes are current online
 */
public class Utils {

    /**
     * The start date of Mythic+ dungeons, helps to know which week we are.
     */
    public static final DateTime startDateMythicPlus = new DateTime(2017,3,28,0,0, DateTimeZone.forID("America/Montreal"));

    public static final Map<String,AffixDescription> affixDescription = new HashMap<>();

    static {
        affixDescription.put("Overflowing", new AffixDescription(1, "Healing in excess of a target's maximum health is instead converted to a heal absorption effect.", 1));
        affixDescription.put("Skittish", new AffixDescription(2, "Enemies pay far less attention to threat generated by tanks. 80% Threat reduction.", 2));
        affixDescription.put("Volcanic",new AffixDescription(3, "While in combat, enemies periodically cause gouts of flame to erupt beneath the feet of distant players.", 0));
        affixDescription.put("Necrotic", new AffixDescription(4, "All enemies' melee attacks apply a stacking blight that inflicts damage over time and reduces healing received.", 2));
        affixDescription.put("Teeming", new AffixDescription(5, "Additional non-boss enemies are present throughout the dungeon.", 1));
        affixDescription.put("Raging", new AffixDescription(6, "Non-boss enemies enrage at 30% health remaining, dealing 100% increased damage until defeated.", 1));
        affixDescription.put("Bolstering", new AffixDescription(7,"When any non-boss enemy dies, its death cry empowers nearby allies, increasing their maximum health and damage by 20%.", 1));
        affixDescription.put("Sanguine", new AffixDescription(8, "When slain, non-boss enemies leave behind a lingering pool of ichor that heals their allies and damages players.", 0));
        affixDescription.put("Tyrannical", new AffixDescription(9, "Boss enemies have 40% more health and inflict up to 15% increased damage.", 2));
        affixDescription.put("Fortified", new AffixDescription(10, "Non-boss enemies have 20% more health and inflict up to 30% increased damage.", 2));
        affixDescription.put("Bursting", new AffixDescription(11, "When slain, non-boss enemies explode, causing all players to suffer 10% of their max health in damage over 4 sec. This effect stacks.", 1));
        affixDescription.put("Grievous", new AffixDescription(12, "When injured below 90% health, players will suffer increasing damage over time until healed above 90% health.", 1));
        affixDescription.put("Explosive", new AffixDescription(13, "While in combat, enemies periodically summon Explosive Orbs that will detonate if not destroyed.", 1));
        affixDescription.put("Quaking", new AffixDescription(14, "Periodically, all players emit a shockwave, inflicting damage and interrupting nearby allies.", 1));
    }

    /**
     * All the Mythic+ affixes groups.
     */
    public static final String[][] mythicPlusAffixes = {
            {"Raging","Volcanic","Tyrannical"},
            {"Teeming","Explosive","Fortified"},
            {"Bolstering","Grievous","Tyrannical"},
            {"Sanguine", "Volcanic","Fortified"},
            {"Bursting", "Skittish", "Tyrannical"},
            {"Teeming","Quaking","Fortified"},
            {"Raging", "Necrotic","Tyrannical"},
            {"Bolstering", "Skittish", "Fortified"},
            {"Teeming", "Necrotic", "Tyrannical"},
            {"Sanguine","Grievous", "Fortified"},
            {"Bolstering", "Explosive", "Tyrannical"},
            {"Bursting", "Quaking", "Fortified"}
    };

    public static final EmbedBuilder createMythicEmbed(String[] weekAffixes) {
        EmbedBuilder eb = new EmbedBuilder();
        eb.setThumbnail("http://wow.zamimg.com/images/wow/icons/large/inv_relics_hourglass.jpg");

        eb.setFooter("Mythic+ Affixes", "http://wow.zamimg.com/images/wow/icons/large/inv_relics_hourglass.jpg");
        AffixDescription affix4 = Utils.affixDescription.get(weekAffixes[0]);
        AffixDescription affix7 = Utils.affixDescription.get(weekAffixes[1]);
        AffixDescription affix10 = Utils.affixDescription.get(weekAffixes[2]);
        int difficulty = affix4.getDifficulty() + affix7.getDifficulty() + affix10.getDifficulty();

        if (difficulty <= 3) {
            eb.setColor(Color.GREEN);
        } else if (difficulty == 4) {
            eb.setColor(Color.YELLOW);
        } else {
            eb.setColor(Color.RED);
        }
        eb.addField("(4) " + weekAffixes[0],affix4.getDescription() + "\n[More Info](http://www.wowhead.com/affix="+affix4.getId()+")",false);
        eb.addField("(7) " + weekAffixes[1],affix7.getDescription() + "\n[More Info](http://www.wowhead.com/affix="+affix7.getId()+")",false);
        eb.addField("(10) " + weekAffixes[2],affix10.getDescription() + "\n[More Info](http://www.wowhead.com/affix="+affix10.getId()+")",false);
        return eb;
    }
}
